import type { Metadata } from "next";
import "@repo/ui/global.css";

import { HeaderLayout } from "app/components/header-layout";
import { Providers } from "app/lib/providers";
import { Roboto } from "next/font/google";
import { baloo2, baloo2ExtraBold } from "public/fonts";

const roboto = Roboto({
	weight: ["700", "400"],
	subsets: ["latin"],
	display: "swap",
	variable: "--font-roboto",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};


export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="pt-BR"
			className={`${roboto.variable} ${baloo2.variable} ${baloo2ExtraBold.variable}`}
		>
			<body>
				<HeaderLayout />
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
