import type { Metadata } from "next";
import "../public/global.css";

import { HeaderLayout } from "app/components/header-layout";
import { Providers } from "app/lib/providers";
import { Baloo_2, Roboto } from "next/font/google";
import localFont from "next/font/local";

const roboto = Roboto({
	weight: ["700", "400"],
	subsets: ["latin"],
	display: "swap",
	variable: "--font-roboto",
});

export const baloo2ExtraBold = localFont({
	src: "../public/Baloo2-ExtraBold.ttf",
	weight: "900",
	display: "swap",
	variable: "--font-baloo2-extrabold",
});

export const baloo2 = Baloo_2({
	weight: ["700", "800"],
	subsets: ["latin"],
	display: "swap",
	variable: "--font-baloo2",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="pt-BR"
			className={`${roboto.variable} ${baloo2.variable} ${baloo2ExtraBold.variable}`}
		>
			<body>
				<HeaderLayout />
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
